[package]
name = "r-clock"
version = "0.1.0"
edition = "2021"
authors = ["Alustrat <pro.alustrat@pm.me>"]

[dependencies]
chrono = "0.4.31"
chrono-tz = "0.8.5"
clap = { version = "4.4.16", features = ["derive"] }
crossterm = "0.27.0"
ctrlc = "3.4.2"
